### ISSUE TITLE
Add ability to get applicable markings for a STIX construct

### ISSUE THREAD

**Issue by bworrell** [STIXProject/python-stix#100]
There should be some mechanism by which a user can determine the applicable markings for a given construct. This could be a `get_markings()` method associated with each `stix.Entity` implementation, or a global `get_markings(...)` or `is_marked(...)` method.

**Comment by emmanvg** [comment]
Super late, but we have released https://github.com/mitre/stixmarx and it provides such ability. Unless there is further discussion on the topic, I am happy with closing this issue.

**Comment by gtback** [comment]
Yep, I'd say we can close this!
