### ISSUE TITLE
Add a stix_package.add(component) method to add top-level components

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/python-stix#137]
Right now you use `stix_package.add_indicator(indicator)`, could we add a helper method called `stix_package.add(indicator)` that would introspect on the type and pass it along to the correct method?

**Comment by bworrell** [comment]
c67c15e caused a problem with `Entity.to_dict()` and was fixed in
51ee36730d36795d858be83967ba3bdb21a5d7de
