### ISSUE TITLE
Make it easier to use Lockheed Martin Kill Chain

### ISSUE THREAD

**Issue by gtback** [STIXProject/python-stix#158]
We've already defined standard IDs for the kill chain and its phases, so it makes sense to make these easier to use from python-stix.

http://stix.mitre.org/language/version1.1.1/stix_v1.1.1_lmco_killchain.xml

**Comment by bworrell** [comment]
@johnwunder, are the IDs used in the sample that @gtback referred to considered to be standard IDs that should always be used when defining a LMCO kill chain in STIX or were they just randomly generated?

**Comment by johnwunder** [comment]
They're considered standard IDs and should always be used.

**Comment by bworrell** [comment]
Thanks!

**Comment by bworrell** [comment]
This was merged, so I'm closing this :)
