### ISSUE TITLE
Add RelatedCampaigns to Indicator

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/python-stix#192]
Right now we support the deprecated approach (Campaign => Indicator) but not the suggested approach (Indicator => Campaign)

**Comment by terrymacdonald** [comment]
Kinda need this right now. Is there a binding API workaround?

**Comment by bworrell** [comment]
@terrymacdonald, unfortunately I don't believe there is a workaround at the moment (short of monkey patching a ton of code). I am currently tackling this issue and will push a commit shortly (unless I hit any major issues).

**Comment by terrymacdonald** [comment]
Top man!

Cheers
Terry MacDonald

**Comment by bworrell** [comment]
@terrymacdonald, I added `related_campaigns` to the `Indicator` class though it still needs some documentation and examples.

**Comment by terrymacdonald** [comment]
Wow Bryan! Just wow. That was so darn fast. I'll try it out later today.

Cheers
Terry MacDonald

**Comment by bworrell** [comment]
Awesome! Let us know if you have any issues. I did push a little example script [**here**](https://github.com/STIXProject/python-stix/blob/master/examples/campaign-reference.py) that shows how to add related campaign references to an `Indicator`.

**Comment by terrymacdonald** [comment]
Hi Bryan,

Works perfectly:

# Create the Campaign Reference
related_campaign_ref = CampaignRef(idref=campaign_id)
indicator.add_related_campaign(related_campaign_ref)

generates (as expected):

            <indicator:Related_Campaigns>
                <indicator:Related_Campaign>
                    <stixCommon:Campaign
idref="example:Campaign-a190ddde-7475-8fb7-479f-503c36f14538"/>
                </indicator:Related_Campaign>
            </indicator:Related_Campaigns>

Cheers
Terry MacDonald

**Comment by malcojosh** [comment]
Thank you for this, I was just trying to figure this out two days ago and finally landed on this ticket. Awesome to see it's been resolved!
