### ISSUE TITLE
Preserve the custom namespace prefixes of the passed document (via a non_stix_dict)

### ISSUE THREAD

**Issue by marlontaylor** [STIXProject/python-stix#200]
One can override STIX namespace aliases on export with the `ns_dict` parameter on `to_xml()`:
```python

# tested on v1.1.1.1

print package.to_xml(ns_dict={'http://stix.mitre.org/stix-1': 'TEST'})
```

 

Non-default namespace aliases are not preserved on a round-trip, so if "http://stix.mitre.org/stix-1" was mapped to a "foo" alias on an input document, that document would be exported with a "stix" namespace alias unless the `ns_dict` parameter remaps that namespace to a non-"stix" alias.  This behavior of the `ns_dict` parameter is only applicable to STIX constructs.

Using the `ns_dict` parameter of the `.to_xml()` method requires the developer to know what prefixes to include. This is easier if you're only creating your own documents but if you're ingesting documents from various creators the developer won't know all of the prefixes beforehand.

Could the stix/utils/parser/EntityParser create a dictionary of all the non-"stix" prefixes, urls, schemalocations? This `non_stix_dict` could then be passed(configurable) to the `.to_xml()` method and the developer wouldn't have to know all possible incoming prefixes. 

Alternatively the developer would have parse the file outside of the API to get this information then create a dictionary and pass it as the ns_dict parameter to the .to_xml() method. Having it in the API would reduce an extra parse and work and the incoming STIX document.

**Comment by bworrell** [comment]
@marlontaylor,

The bindings and other API code rely on statically defined `xsi:type

**Comment by bworrell** [comment]
@marlontaylor 

I refactored the namespace parsing code in 70a91bc7950eb8ed4702a984d71fc619b007d285 to allow multiple namespace prefixes for a given namespace. 

So doing something like:
```python
from stix.core import STIXPackage
package = STIXPackage()
print package.to_xml(ns_dict={'http://stix.mitre.org/stix-1': 'foo'})
```
Will yield a STIX document with both a `stix` and `foo` namespace prefix mapped to `http://stix.mitre.org/stix-1`:

```xml
<stix:STIX_Package
        <!-- SNIP -->
        xmlns:foo="http://stix.mitre.org/stix-1"
        xmlns:stix="http://stix.mitre.org/stix-1"
        <!-- SNIP -->
        id="example:Package-8ecea94f-b4e9-4cfc-9e63-151cf08b43ed" version="1.1.1" timestamp="2015-04-09T15:36:13.410831+00:00"/>

```

Non-default namespace mappings are preserved on round trip as well:

```python
import StringIO
from stix.core import STIXPackage

XML = \
"""
<stix:STIX_Package
        xmlns:example="http://example.com"
        xmlns:foo="http://stix.mitre.org/stix-1"
        xmlns:stix="http://stix.mitre.org/stix-1"
        id="example:Package-8ecea94f-b4e9-4cfc-9e63-151cf08b43ed" 
        version="1.1.1" 
        timestamp="2015-04-09T15:36:13.410831+00:00"/>
"""

readable = StringIO.StringIO(XML)
package = STIXPackage.from_xml(readable)
print package.to_xml()
```

This prints:
```xml
<stix:STIX_Package
        <!-- SNIP --->
        xmlns:foo="http://stix.mitre.org/stix-1"
        xmlns:stix="http://stix.mitre.org/stix-1"
        <!-- SNIP -->
        id="example:Package-8ecea94f-b4e9-4cfc-9e63-151cf08b43ed" 
        version="1.1.1" 
        timestamp="2015-04-09T15:36:13.410831+00:00"/>
```


We still don't allow the remapping of default prefixes to non-default namespaces (that is, you can't remap `indicator` to `http://foobar.org`) as this would result in `xsi:type` lookup errors.

I think this addresses your issue, so I am going to close this. If not, we can reopen it and discuss!
