### ISSUE TITLE
to_xml of STIX entity ignores additional entries in ns_dict

### ISSUE THREAD

**Issue by bgro** [STIXProject/python-stix#224]
When auto_namspace is set to True in the to_xml-method, then ns_dict is completely ignored. The ns_dict, however, seems to be the only way to add namespace information other than the namspace of the entity identifer. For example, I create a STIX object with entities for which I set the idref-Attribute to "some_other_ns:identifier". In earlier STIX versions, I would add an entry mapping the URL associated with the "some_other_ns" to the ns_dict, and it would be included in the namespaces. Now, the namespace are pruned nicely, but this additional namespace is left out.

Would it be possible to add an option with which the inclusion of the namespaces passed in ns_dict is forced? Or is there some other way of adding namespace info that I am overlooking?

**Comment by jap** [comment]
:thumbsup: also being bit by this issue, do you have any updates on this?

**Comment by bworrell** [comment]
This was fixed in #238
