### ISSUE TITLE
Implement multiple descriptions

### ISSUE THREAD

**Issue by bworrell** [STIXProject/python-stix#247]
This is in reference to https://github.com/STIXProject/schemas/issues/186

* Add support for `@ordinality` on `stix.common.StructuredText`
* Add `descriptions` property to places where there is a `description` property.
  * `description` becomes a sort of `descriptions[0]`
  * `descriptions` returns an ordered list, sorted by `ordinality`
  * `descriptions` could be a mapping type, keyed off of `ordinality` rather than raw index (this might be kinda weird in use).

**Comment by gtback** [comment]
Agree. `descriptions` can return a custom object that defines `__iter__` for returning the descriptions in sorted order, and `__getitem__` to look up a particular description by ID or ordinality. User shouldn't need to index items directly by their position (prefer `for desc in text.descriptions:`), but could do `list(text.descriptions)[2]` if necessary. `description` can be a property that returns the first item in the list, which should preserve backward-compatible behavior.

We'll probably need an add_description on types that allow multiple descriptions. We should determine exactly how that might work .
