### ISSUE TITLE
Incongruity between Campaign/CampaignRef Timestamps

### ISSUE THREAD

**Issue by ikiril01** [STIXProject/python-stix#251]
I noticed recently that there's an incongruity between timestamp values when using the auto-generated value in a Campaign and then using this value in a CampaignRef. Essentially, the auto-generated timestamp value includes an extra "+00:00" timezone value instead of just using the Zulu time specification ("Z"). This causes a mismatch between the two values which can show up in best-practice validation using the `stix-validator`. 

E.g., the Campaign timestamp would be `2015-04-14T14:46:59.026098+00:00`, and the referenced value would be `2015-04-14T14:46:59.026098Z`. 

Here's some code that will reproduce the issue:

```python
from stix.campaign import Campaign
from stix.core import STIXPackage
from stix.common import CampaignRef
from stix.indicator import Indicator

c = Campaign()
cref = CampaignRef(idref=c.id_,timestamp=c.timestamp)
i = Indicator()
i.add_related_campaign(cref)
stix_package = STIXPackage()
stix_package.add_campaign(c)
stix_package.add_indicator(i)

```

Also, here's the type of output that the `stix-validator` gives with regards to this:

```
[!] Timestamp Use
        [-] line : 25
        [-] message : IDREF and timestamp combination do not resolve to a node in the input document.
        [-] id : None
        [-] idref : example:campaign-a442247b-347b-4062-a79d-cf2fe8169ef0
        [-] tag : {http://stix.mitre.org/common-1}Campaign
        [-] timestamp : 2015-04-14T14:55:39.469562Z
```

**Comment by bworrell** [comment]
@ikiril01, looks like the `CampaignReference` class wasn't passing the `timestamp` value to the bindings correctly. It should be all set now!

**Comment by ikiril01** [comment]
@bworrell sweet! Glad it was a quick/simple fix :)

**Comment by bworrell** [comment]
@ikiril01, it was a simple fix here but got me thinking about how the stix-validator does timezone/timestamp checks.

I pushed a bunch of commits that make the `Timestamp Use
