### ISSUE TITLE
Update VocabString classes to use STIX 1.2 vocabs

### ISSUE THREAD

**Issue by bworrell** [STIXProject/python-stix#255]

**Comment by bworrell** [comment]
I believe this is all finished up. I added a `Versioning` vocab class and updated `DiscoveryMethod`

**Comment by johnwunder** [comment]
Do you need to add `ReportIntent`? It's a duplicate of `PackageIntent` but for `Report`.

**Comment by bworrell** [comment]
I forgot to mention it in my comment, but it's already added :)
