### ISSUE TITLE
Update nsparser dictionaries for 1.2

### ISSUE THREAD

**Issue by bworrell** [STIXProject/python-stix#258]
- [x] Update schemalocations
- [x] Added Report Object namespace to namespace dictionaries

**Comment by bworrell** [comment]
Implemented in commit: 667611a4f32654688aabc5a8d0c5c125b3423c93

**Comment by gtback** [comment]
@gtback is :confused: Did you mean to reopen this one or #260?

**Comment by bworrell** [comment]
Haha, I reopened this one because I realized that I missed the schemalocations dictionary in `nsparser.py` (and have since updated).

**Comment by bworrell** [comment]
With this commit I think I'm done with this issue: 015e5e504148222288a843e3072886053d97cdca
