### ISSUE TITLE
Export as different version

### ISSUE THREAD

**Issue by geekscrapy** [STIXProject/python-stix#268]
Is it possible to export to a different version (say 1.1) instead of the default 1.2? Or would I have to use a previous version of the code?

**Comment by bworrell** [comment]
@geekscrapy, you'd need to use a `v1.1.1.x` release of python-stix.

**Comment by geekscrapy** [comment]
ok thanks. I know its not ideal but I did use STIXHeader.version to a valid version which was successfully imported into the intel platform i'm using, works, just cant use the updates to the standard!
