### ISSUE TITLE
STIXPackage.version does not stick when set

### ISSUE THREAD

**Issue by geekscrapy** [STIXProject/python-stix#269]
I've been trying to set the version value in the STIX package however when it is output to XML the value is always 1.2

    pkg = stix.core.stix_package.STIXPackage()
    pkg.version
    '1.2'
    pkg.version = '1.1'
    pkg.version
    '1.1'
    pkg.to_xml()
    '<stix:STIX_Package \n\txmlns:cybox="http://cybox.mitre.org/cybox-    2"\n\txmlns:cyboxCommon="http://cybox.mitre.org/common-    2"\n\txmlns:cyboxVocabs="http://cybox.mitre.org/default_vocabularies-    2"\n\txmlns:example="http://example.com"\n\txmlns:stix="http://stix.mitre.org/stix-    1"\n\txmlns:stixCommon="http://stix.mitre.org/common-    1"\n\txmlns:stixVocabs="http://stix.mitre.org/default_vocabularies-    1"\n\txmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="example:Package-8578476b-c663-    4845-bd37-e5dfd92a4c7c" version="1.2"/>\n'

**Comment by gtback** [comment]
It looks like we explicitly override whatever the user sets as the version when serializing [to xml](https://github.com/STIXProject/python-stix/blob/05342c66a5e3291838b373ff88586062df3036c4/stix/core/stix_package.py#L405) and [to a dictionary](https://github.com/STIXProject/python-stix/blob/05342c66a5e3291838b373ff88586062df3036c4/stix/core/stix_package.py#L436-L437). 

@bworrell If this is true, should we remove the `version` property altogether, or make it read-only? Are we trying to support parsing older content in case it's still valid with the new schema?

@geekscrapy: I'm guessing this is related to #268? In general, our advice is to use an older version of python-stix if you're trying to export a previous version of STIX. We know that's not always a good (or feasible) approach, but maintaining multiple, slightly different versions of the same types in the same library would be an enormous challenge for us. If you could tell us a bit more about what you're trying to do (either comment in this issue or send an email to stix@mitre.org), we can try to help come up with a solution. 

Thanks!

**Comment by bworrell** [comment]
@gtback, @geekscrapy: the behavior of the `version` property mostly stems from the tight coupling of STIX and python-stix versions (as @gtback mentioned.) By using python-stix v1.2.0.0, you are creating STIX v1.2 content.

For example, If you export a document as `my_package.to_xml(include_schemalocs=True)` you're going to see STIX 1.2 schema locations in your output; you are able to interact and set STIX 1.2 fields (e.g., multiple `Description` fields); the controlled vocabulary fields default to the latest controlled vocabularies (including 1.2 vocabularies). Everything is just sorta positioned for the creation of STIX 1.2 content, so why be able to set it at all?

python-stix v1.2.0.0 is the first version to natively parse more than one version of STIX content: v1.1.1 and v1.2. I wanted users to be able to retrieve the version of the parsed content by inspecting the `version` property (answering the question, "was this a 1.1.1 document or a 1.2 document?") but force the creation of 1.2 content by overriding the property value during serialization. After all, if you parse a v1.1.1 document and then add [multiple descriptions](https://github.com/STIXProject/schemas/wiki/Proposal:-Allow-Multiple-Descriptions) to an object, it is no longer 1.1.1 valid.

@gtback, maybe we should make the `version` attribute readonly. I imagine it can be set internally during parse (in case we are ingesting v1.1.1 content) but just reports `1.2` normally.

**Comment by gtback** [comment]
:+1: for readonly. But with the changes to TypedFields, it might be additional work :smile:

**Comment by geekscrapy** [comment]
Hi, chucking in my 2 cents

I basically wanted to be able to set the version as I am mindful of what objects/relationships I create and use (I can choose to only implement valid STIX version 1.1 objects correct?) and so all that's actually invalid with my particular output is the version number.

For completeness, I'm creating STIX in python-stix 1.2 and trying to import into Soltra Edge which currently only supports 1.1, hence the need to change the version on the fly.

**Comment by gtback** [comment]
If you're trying to support STIX 1.1, you're best off using an older version of python-stix. See [this page](https://stix.readthedocs.org/en/stable/) for the most recent version of python-stix for each STIX version. We do add features and fix bugs in new versions of python-stix, in addition to upgrading our language support; though we haven't backported many features in the past, if it's critical enough we will consider doing so. Just let us know.

**Comment by chorsley** [comment]
We'd also like to generate both STIX 1.1.1 and 1.2 on demand, but running multiple versions of a library side by side doesn't play well with pip / virtualenv's normal operation. Is there any possibility of making the STIX version generated explicit in the package name to avoid namespace clashes, e.g. ```stix-1.2``` and ```stix-1.1.1```? These could alternatively be used in parallel with the latest version in the ```stix``` package.
