### ISSUE TITLE
BaseCoreComponent should not have information_source field

### ISSUE THREAD

**Issue by bworrell** [STIXProject/python-stix#277]
`IndicatorType` does not have an `Information_Source` field and instead has a `Producer` field. Currently, `indicator.Indicator` has both of these, which is not correct.

**Comment by emmanvg** [comment]
I think this issue has been fixed for both 1.1.1.X and 1.2.0.X when TypedFields got implemented... Are we okay with closing this @gtback?

**Comment by gtback** [comment]
Yep, this can be closed.
