### ISSUE TITLE
Updated from python-Stix 1.2.0.0 to latest and set_id_namespace breaks

### ISSUE THREAD

**Issue by terrymacdonald** [STIXProject/python-stix#284]
Hi,

I just updated from python-Stix 1.2.0.0 to with a 'pip install --update stix' and set_id_namespace breaks on any script that sets a custom namespace. Pip installed 1.2.0.1dev3 and it broke. Any of the 1.2.0.1devX versions are broken. I had to manually rollback to python-stix 1.2.0.0 (and the matching Cybox) for the scripts to work again.

Cheers
Terry MacDonald

**Comment by gtback** [comment]
@terrymacdonald: What version of pip are you using? New-ish versions of pip won't install the "pre-release" versions of packages (in other words, those with `dev`).

I realize that's not a great answer, but hopefully upgrading pip once is easier than remembering to install explicit versions of python-cybox and python-stix every time.

**Comment by michaelpepin** [comment]
backwards compatibility python-stix 1.2.0.0  to  python-stix 1.2.0.1 
(I assumed that a dot release **would not break** backwards compatibility, is this an error or a policy?)

first ones I hit was idgen 
- moved  stix.utils.idgen to cybox.mixbox.idgen

**Comment by gtback** [comment]
Yes, 1.2.0.1 is not backward compatible with 1.2.0.0 in areas like this. Our versioning policy is that the first 3 components correspond to the version of STIX that the library supports, meaning that we only have one component to use for sequential releases (without going to 5 components). 

In some cases (like `set_id_namespace`) we could probably add a wrapper to preserve compatibility, but for bigger issues like namespaces in general it will be difficult. Part of the problem with unifying how cybox, stix, and maec handle namespaces (via mixbox) is some incompatibilites crop up. 

One of my goals was to make updating to 1.2.0.1 as seamless as possible, knowing that there would be minor issues like this. An alternative is to pin version 1.2.0.0 and the corresponding cybox (2.1.0.12)
