### ISSUE TITLE
DDoS Format

### ISSUE THREAD

**Issue by c2theg** [STIXProject/python-stix#290]
I'm looking for a DDoS formatted message. for both Incidents and threat actors.  Is there a plan to make one as i can not find an existing one.

Thanks

**Comment by gtback** [comment]
Hi, @c2theg, thanks for the question.

Are you talking about an example STIX document describing a DDoS attack? Are you talking about the STIX (XML) itself, or Python code to create that XML? Either way, I don't know of anything at the moment. If it's a general XML question, you might have more luck asking the [cti-users](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback) list at OASIS. If it's a Python-specific question, this is the best place.

**Comment by c2theg** [comment]
I was more asking about DDoS campaigns, in a XML format. Not python at
all.  If there is one, could you please direct me to it?

Thanks,
Chris

On Mon, Apr 25, 2016 at 10:12 AM, Greg Back <notifications@github.com>
wrote:

> Hi, @c2theg <https://github.com/c2theg>, thanks for the question.
>
> Are you talking about an example STIX document describing a DDoS attack?
> Are you talking about the STIX (XML) itself, or Python code to create that
> XML? Either way, I don't know of anything at the moment. If it's a general
> XML question, you might have more luck asking the cti-users
> <https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback>
> list at OASIS. If it's a Python-specific question, this is the best place.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/STIXProject/python-stix/issues/290#issuecomment-214351516>
>



-- 
Thanks,
Christopher Gray

**Comment by gtback** [comment]
@c2theg, I'd recommend subscribing to the `cti-users` list (see the link above), and asking the community there. I'm not aware of any example STIX documents for DDoS, but it's likely someone there might.

I'm going to close this since it's not specific to python-stix. Thanks again!
