### ISSUE TITLE
Support for organisation info in STIXCIQIdentity 

### ISSUE THREAD

**Issue by MatthewCarr94** [STIXProject/python-stix#292]
Add support for organisation info in to_dict() and from_dict() methods in STIXCIQIdentity3_0 class

**Comment by michaelpepin** [comment]
+1    (for people in the US/Canada searching for this: organization)

**Comment by gtback** [comment]
Thanks, @MatthewCarr94 and @michaelpepin. 

The STIX team is pretty busy working on STIX 2.0, but we will take a look at this when we get a chance. If either of you has a chance to implement it and submit a pull request, that would be greatly appreciated! 😀

**Comment by MatthewCarr94** [comment]
See: [PR 293](https://github.com/STIXProject/python-stix/pull/293). Thanks!

**Comment by gtback** [comment]
Fixed by #293
