### ISSUE TITLE
Non-Default Vocabulary Terms

### ISSUE THREAD

**Issue by ambrous** [STIXProject/python-stix#295]
Hi!

I add non-default vocabulary term (as said there http://stix.readthedocs.io/en/latest/overview/controlled_vocabularies.html#non-default-vocabulary-terms):

```
incident = Incident()
non_default_term = VocabString('non-default vocabulary term')
incident.categories.append(non_default_term)

```

but I have a folow error:

Value must be one of ('Exercise/Network Defense Testing', 'Malicious Code', 'Improper Usage', 'Unauthorized Access', 'Denial of Service', 'Scans/Probes/Attempted Access', 'Investigation'). Received 'non-default vocabulary term'

But example https://github.com/STIXProject/python-stix/blob/master/examples/vocabstrings.py is work!
Where did I mistake?

Thanks!

**Comment by gtback** [comment]
Hi @ambrous, thanks for the question.

What versions of the libraries are you using? Are you using the master branch or the most recent release (1.2.0.0)?

For me, in an environment with the following installed:
```
cybox (2.1.0.12)
lxml (3.6.0)
python-dateutil (2.5.3)
six (1.10.0)
stix (1.2.0.0)
```

The following code runs without error:

```python
from stix.incident import Incident
from stix.common.vocabs import VocabString

incident = Incident()
non_default_term = VocabString('non-default vocabulary term')
incident.categories.append(non_default_term)
print incident.to_xml()
```

If it's still not working for you, could you provide some more information about your environment (operating system, Python version, library versions, etc.) to help us reproduce it? Thanks!

**Comment by ambrous** [comment]
@gtback, thank you very much for your answer!

My environment:

```
cybox (2.1.0.12)
lxml (3.6.0)
python-dateutil (2.5.1)
six (1.10.0)
stix (1.2.0.0)
```

I resolved problem, cause were in follow:
in variable **non_default_term** wrote object of class **cybox.common.vocabs.VocabString**, but must be **stix.common.vocabs.VocabString**, although I imported only "from stix.common.vocabs import VocabString" and I did not import cybox.common.* classes. 

In total I added alias for import and it became work:
`from stix.common.vocabs import VocabString as StixVocabString`

**Comment by gtback** [comment]
Ah, glad you figured it out! 😀
