### ISSUE TITLE
Fix for setting default ID namespace?

### ISSUE THREAD

**Issue by RobNoVA** [STIXProject/python-stix#301]
As per http://stix.readthedocs.io/en/stable/overview/id_namespaces.html, setting a new default ID namespace appears to be broken in 1.2.0.1.  The error is "ImportError: cannot import name set_id_namespace"

Using python 2.7.12 on Win7 64-bit.

**Comment by gtback** [comment]
Yes, this is a bug in the documentation. This changed between 1.2.0.0 and 1.2.0.1, and the documentation wasn't updated.

**Comment by clenk** [comment]
Yes, things got moved around a little. Please see the updated example at [http://stix.readthedocs.io/en/latest/overview/id_namespaces.html](http://stix.readthedocs.io/en/latest/overview/id_namespaces.html) which involves importing set_id_namespace from [mixbox](https://github.com/CybOXProject/mixbox).

**Comment by gtback** [comment]
Thanks, @clenk
