### ISSUE TITLE
Indicator.observables returns empty list when one observable

### ISSUE THREAD

**Issue by kralca** [STIXProject/python-stix#309]
Contrary to the comments in stix.indicator.indicator.Indicator, which states:

>             If only one Observable is set, this property will return a list
>             with the ``observable`` property.

Potential solution:

```
        if self.observable:
            return [self.observable]
        elif self.observable.observable_composition:
            return self.observable.observable_composition.observables

        return []
```

**Comment by gtback** [comment]
Thanks, @kralca !
