### ISSUE TITLE
Encoding issues in to_xml

### ISSUE THREAD

**Issue by gtback** [STIXProject/python-stix#314]
There's some type of bug in to_xml that is causing it to behave differently than I expected. That's why for Python 3 you need to pass `encoding=None` as seen in https://github.com/STIXProject/stixproject.github.io/pull/336#issuecomment-270966808.

This is fairly low priority, but I wanted to record it so I don't forget about it.

**Comment by emmanvg** [comment]
This problem is present in stix.Entity.to_xml() as well as the mixbox.Entity.to_xml(). I will open an issue for that one.

**Comment by gtback** [comment]
I think that what I saw as a "bug" was that Python 3 doesn't allow you to `print()` a byte string (`bytes` type), only a Unicode text `str`, but Python 2 allows you to print either Unicode text (`unicode`) or a byte string (`str`). Based on that, there's nothing we can fix here. For backwards compatibility, `to_xml()` should continue to return UTF-8 bytes by default, and we can provide better guidance on how to display that value within the idioms on stixproject.github.io.
