### ISSUE TITLE
Can't link stuff and documentation sucks.

### ISSUE THREAD

**Issue by RomanFire1** [STIXProject/python-stix#315]
We want to link behavior of an attack pattern to a ttp so we can get it back out as an xml but there is nothing showing or telling how the hell to do it.

**Comment by athiasjerome** [comment]
RTFM
https://stixproject.github.io/documentation/idioms/leveraged-ttp/
https://stixproject.github.io/documentation/idioms/leveraged-ttp/threat-actor-leveraging-attack-patterns-and-malware_producer.py

**Comment by gtback** [comment]
If there are specific questions you have after reviewing the links from @athiasjerome, let me know, but otherwise I'm going to close this.
