### ISSUE TITLE
Add documentation for how to use AIS markings

### ISSUE THREAD

**Issue by gtback** [STIXProject/python-stix#326]

**Comment by emmanvg** [comment]
Add some code examples.

**Comment by gtback** [comment]
Add to the parsing example showing how to parse out:

-	proprietary
-	consent
-	color
-	country_name_code
-	country_name_code_type
-	admin_area_name_code
-	admin_area_name_code_type
-	organisation_name
-	industry_type

Also, ensure this is available in both the 1.1.1.x and 1.2.0.x docs

**Comment by gtback** [comment]
The 1.1.1 docs now show this: https://stix.readthedocs.io/en/stix1.1.1/api/extensions/marking/ais.html
