### ISSUE TITLE
Create multiple "contacts" in "Incident"

### ISSUE THREAD

**Issue by AjayS91** [STIXProject/python-stix#337]
[Incident](https://github.com/STIXProject/python-stix/blob/master/stix/incident/__init__.py)
> contacts = fields.TypedField("Contact", InformationSource, multiple=True, key_name="contacts")
Above field is specified in "Incident" class but there is no function or procedure to add multiple contacts.

Is there any workaround for it?

**Comment by gtback** [comment]
Thanks, @AjayS91 . `Incident().contacts` should behave just like a normal Python list (you can `append`, etc.), or you can just set it to a list of `InformationSource` objects. Does that not work?

**Comment by AjayS91** [comment]
Thanks, @gtback.It worked like charm.

**Comment by gtback** [comment]
Good to hear, @AjayS91 . I'm going to close this issue, since it sounds like it's working for you; if not, feel free to re-open.
