### ISSUE TITLE
to_json fails on parsing datetime

### ISSUE THREAD

**Issue by chrisr3d** [STIXProject/python-stix#342]
I tried to parse the following stix document using to_json:
https://www.eclecticiq.com/downloads/EclecticIQ-Fusion-Center-Report-Thanatos-Ransomware.zip
But it seems like there is a problem with datetime with both python 2.7 and 3.6

![screenshot from 2018-02-27 15-34-30](https://user-images.githubusercontent.com/16307976/36740036-a05f8eda-1be1-11e8-94ea-4e0b742404c4.png)

![screenshot from 2018-02-27 15-38-08](https://user-images.githubusercontent.com/16307976/36740083-b9e4e472-1be1-11e8-942c-6d4698c2bc27.png)

**Comment by gtback** [comment]
Thanks, @chrisr3d, we'll take a look.

**Comment by emmanvg** [comment]
Hi @chrisr3d! Thanks for the submission. I was able to test and confirm this is happening in both PY2 and PY3. Good news, this is a simple fix in https://github.com/STIXProject/python-stix/blob/master/stix/report/__init__.py#L62. This field should be a `DateTimeField` not a regular `TypedField`. The next release of stix 1.2.0.X should include this fix!

**Comment by chrisr3d** [comment]
Okay, thanks a lot @gtback @emmanvg
