### ISSUE TITLE
Deleted methods from python-stix/stix/ttp/victim_targeting.py

### ISSUE THREAD

**Issue by ambrous** [STIXProject/python-stix#347]
Hi!

Could you tell why the property of **targeted_technical_details** has been removed from VictimTargeting class in python-stix/stix/ttp/victim_targeting.py ?

I am using this property, but in the current version of 1.2 it is not available. It just disappeared from our packages without any errors.

Thanks a lot!

**Comment by emmanvg** [comment]
Hey @ambrous! Thanks for the submission. I checked the history for this file and to be honest I have no idea why **targeted_technical_details** was left out. My only guess is that it was not possible to be converted into a `TypedField` at the time. The good part is that it should be a simple fix.
