### ISSUE TITLE
About Impact_Qualification issue

### ISSUE THREAD

**Issue by Sue1990** [STIXProject/python-stix#368]
Does anyone know how to compile this (below down XML format)? 

![截圖 2021-04-15 下午8 22 28](https://user-images.githubusercontent.com/39720327/114868310-56f96f00-9e28-11eb-931d-02a944ddc44c.png)

I have tried the below down script, but it didn't work

//This is a test script (this script is right)
impact = ImpactAssessment()
impact.effects = Effects("Unintended Access")
breach.impact_assessment = impact

//This is test script(I think it will be the same impact.effects,but it didn't work)
impact.Qualifications = ImpactQualification()

**Comment by chisholm** [comment]
How about this:

```python
impact.impact_qualification = ImpactQualification("Distracting")
```

`2` would not work since it's not a member of the [ImpactQualification vocabulary](https://stix.readthedocs.io/en/stable/api/common/vocabs.html#stix.common.vocabs.ImpactQualification_1_0).
