### ISSUE TITLE
Add XML string parsing support

### ISSUE THREAD

**Issue by MrAsimZahid** [STIXProject/python-stix#370]
I found there isn't support for parsing XML string. Could you please add support for it?

I don't want to download and then pass the stix.xml file to 
```
STIXPackage.from_xml('stix.xml')
```

instead, I want to pass stix text(str) data directly to ```to_xml``` and process further.
Could you please show me a way, if it's already available? I am unable to finger it out.
Thanks.

**Comment by clenk** [comment]
Hi @MrAsimZahid thanks for the question. `to_xml()` can take "a file, file-like object, etree._Element, or etree._ElementTree instance" as input.

You can turn a string into a file-like object by putting it in a `StringIO`. Such as in [this example from our tests](https://github.com/STIXProject/python-stix/blob/master/stix/test/utils/parser_test.py#L13-L23):

```python
from io import StringIO

def test_valid(self):
    valid = """
    <stix:STIX_Package xmlns:stix="http://stix.mitre.org/stix-1"
        version="1.2" id="example:Package-1">
    </stix:STIX_Package>
    """

    parser = EntityParser()
    package = parser.parse_xml(StringIO(valid))
```

**Comment by MrAsimZahid** [comment]
Thank you @clenk. It worked perfectly.
